version: 2

models:
  - name: dim_teams
    columns:
      - name: team_abbrev
        tests:
          - unique
          - not_null
      - name: team_name
        tests:
          - not_null
      - name: conference_name
        tests:
          - not_null
          - accepted_values:
              values: ["Eastern", "Western"]
      - name: division_name
        tests:
          - not_null
          - accepted_values:
              values: ["Atlantic", "Metropolitan", "Central", "Pacific"]

  - name: dim_players
    columns:
      - name: player_id
        tests:
          - unique
          - not_null
      - name: full_name
        tests:
          - not_null
      - name: position_group
        tests:
          - not_null
          - accepted_values:
              values: ["Forward", "Defenseman", "Goalie"]
      - name: team_abbrev
        tests:
          - not_null
          - relationships:
              to: ref('dim_teams')
              field: team_abbrev

  - name: fct_plays
    columns:
      - name: game_id
        tests:
          - not_null
      - name: event_id
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null
      - name: game_date
        tests:
          - not_null
